#!/bin/sh
# kvmcap: HDMI capture (MJPEG) streaming server for the IP-KVM.

DAEMON=/root/kvmcap/kvmcap
PIDFILE=/var/run/kvmcap.pid
ARGS="-syslog -size 1280x720 -sizes 1280x720,1920x1080 -fps 30 -listen :8081"

case "$1" in
start)
	echo "Starting kvmcap"
	start-stop-daemon -S -b -m -p $PIDFILE -x $DAEMON -- $ARGS
	;;
stop)
	echo "Stopping kvmcap"
	start-stop-daemon -K -p $PIDFILE -x $DAEMON -s TERM
	# Wait for it to release the USB device and rebind uvcvideo.
	for i in 1 2 3 4 5 6 7 8 9 10; do
		[ -d /proc/$(cat $PIDFILE 2>/dev/null) ] || break
		sleep 0.5
	done
	rm -f $PIDFILE
	;;
restart)
	"$0" stop
	"$0" start
	;;
*)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac
